spring.application.name=pedido

server.port=8081

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/microservice-pedido}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}

spring.rabbitmq.addresses=${RABBITMQ_ADDRESSES:}
broker.queue.processamento.name=${RABBITMQ_PROCESSING_QUEUE:}

management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always
management.metrics.enable.all=true

springdoc.show-actuator=true
